{% set name = "edfio" %}
{% set version = "0.4.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/edfio-{{ version }}.tar.gz
  sha256: c072c37f62ec994e277bfa60200805a9cec1e0f2f8bc15c40af692d3902f891c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.22.0

test:
  imports:
    - edfio
  commands:
    - pip check
    - python -c "import edfio; assert edfio.__version__ == '{{ version }}', edfio.__version__"
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/the-siesta-group/edfio
  summary: Read and write EDF/EDF+ files.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DerPhysikeR
    - marcoross
    - hofaflo
